### ISSUE TITLE
Plugin issues cause all devices to be be unresponsive, bridges must be deleted and all re-added to Homekit

### ISSUE THREAD

**Issue by saiajin** [hoobs-org/hoobsd#34] opened 2021-04-12 06:45 UTC
HI, so every time i have a plugin issue.... all plugins/bridges stop responding in Homekit...hoobs runs fine but even after delete of said plugins and reboot of hub... I have to delete all bridges from homekit  and re-add them and all devices... and its more tedious than the old way when the whole thing would go down and then once fixed devices would reconnect and respond again....any one else see this?

**Comment by mkellsy** [comment] 2021-04-12 15:27
Duplicate of #33

**Closed by mkellsy** 2021-04-12 15:27 UTC

**Comment by saiajin** [comment] 2021-04-12 20:40
Didn't see it thank you!
