### ISSUE TITLE
4.0.44: All 4 Bridges reporting this error in the logs, EAddress in use on their respective ports

### ISSUE THREAD

**Issue by themick4u** [hoobs-org/hoobsd#39] opened 2021-04-15 13:37 UTC
4/14/2021, 11:36:24 AMMyQErrorError: listen EADDRINUSE: address already in use 0.0.0.0:51333 at Server.setupListenHandle [as _listen2] (net.js:1318:16) at listenInCluster (net.js:1366:12) at Server.listen (net.js:1452:7) at EventedHTTPServer.listen (/usr/lib/hoobsd/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:155:20) at HAPServer.listen (/usr/lib/hoobsd/node_modules/hap-nodejs/src/lib/HAPServer.ts:316:21) at Bridge.Accessory.publish (/usr/lib/hoobsd/node_modules/hap-nodejs/src/lib/Accessory.ts:1231:18) at Server.publishBridge (/usr/src/bridge/server.ts:323:21) at Server.start (/usr/src/bridge/server.ts:252:14)4

4/15/2021, 9:30:38 AMDummy BridgeErrorError: listen EADDRINUSE: address already in use 0.0.0.0:51666 at Server.setupListenHandle [as _listen2] (net.js:1318:16) at listenInCluster (net.js:1366:12) at Server.listen (net.js:1452:7) at EventedHTTPServer.listen (/usr/lib/hoobsd/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:155:20) at HAPServer.listen (/usr/lib/hoobsd/node_modules/hap-nodejs/src/lib/HAPServer.ts:316:21) at Bridge.Accessory.publish (/usr/lib/hoobsd/node_modules/hap-nodejs/src/lib/Accessory.ts:1231:18) at Server.publishBridge (/usr/src/bridge/server.ts:323:21) at Server.start (/usr/src/bridge/server.ts:252:14)4

4/15/2021, 9:30:39 AMCamerasErrorError: listen **EADDRINUSE: address already in use 0.0.0.0:51877** at Server.setupListenHandle [as _listen2] (net.js:1318:16) at listenInCluster (net.js:1366:12) at Server.listen (net.js:1452:7) at EventedHTTPServer.listen (/usr/lib/hoobsd/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:155:20) at HAPServer.listen (/usr/lib/hoobsd/node_modules/hap-nodejs/src/lib/HAPServer.ts:316:21) at Bridge.Accessory.publish (/usr/lib/hoobsd/node_modules/hap-nodejs/src/lib/Accessory.ts:1231:18) at Server.publishBridge (/usr/src/bridge/server.ts:323:21) at Server.start (/usr/src/bridge/server.ts:252:14)4/15/2021, 9:30:38 AMMyQLoaded plugin 'homebridge-myq'

4/15/2021, 9:30:41 AMHubitat Maker API BridgeErrorError: **listen EADDRINUSE: address already in use 0.0.0.0:51844** at Server.setupListenHandle [as _listen2] (net.js:1318:16) at listenInCluster (net.js:1366:12) at Server.listen (net.js:1452:7) at EventedHTTPServer.listen (/usr/lib/hoobsd/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:155:20) at HAPServer.listen (/usr/lib/hoobsd/node_modules/hap-nodejs/src/lib/HAPServer.ts:316:21) at Bridge.Accessory.publish (/usr/lib/hoobsd/node_modules/hap-nodejs/src/lib/Accessory.ts:1231:18) at Server.publishBridge (/usr/src/bridge/server.ts:323:21) at Server.start (/usr/src/bridge/server.ts:252:14)4

**Comment by themick4u** [comment] 2021-04-15 15:10
Update: I updated the rpi-eeprom with latest update and rebooted and logs appear quiet now, at this moment. Not sure if that cleared up the errors or if they will crop up again

**Comment by mkellsy** [comment] 2021-04-16 16:16
This is actually a duplicate of #38

**Closed by mkellsy** 2021-04-16 16:16 UTC
