### ISSUE TITLE
homebridge-shelly, bridge stop

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/hoobsd#20] opened 2021-03-23 18:33 UTC
Reproduction Steps
1. on a fresh install
2. install the homebridge-shelly plugin in a new bridge
3. it starts the bridge and stops after some seconds

[log (2).txt](https://github.com/hoobs-org/hoobsd/files/6191993/log.2.txt)

**Comment by mkellsy** [comment] 2021-03-23 18:46
Reproduction Steps?

Looks like you hammered something and a Node process got stuck. I don't know this because you didn't include reproduction steps.

Closing task

**Comment by mkellsy** [comment] 2021-03-25 02:29
Shelly is one of those wired plugins that won't start if there is another shelly plugin running on the same port on the same network. This is a plugin issue and not an issue with hoobsd.

I am closing this, but we will keep an eye on this after it's released.

**Closed by mkellsy** 2021-03-25 02:29 UTC
