### ISSUE TITLE
FordPass HOOBS interaction issue

### ISSUE THREAD

**Issue by ballakers** [hoobs-org/hoobsd#28] opened 2021-04-01 17:50 UTC
Sorry unable to provide logs since completely locked out before logs screen could load.  I successfully added fordpass plugin to an empty bridge (not errors said it was configuring my truck accessory) but then when adding this bridge to the home app it just spins and spins. So I tried renaming bridge and also changed the set-up code and gave it a new MAC address and restarted bridge after saving settings and then locked out from immediately, all 3 other bridges down also since no response in home app.  Recovery terminal @9090 also can't be reached as well as ssh
"Blakes-Mac-mini:~ bmckella$ ssh hoobs@192.168.5.72
sudo reboot"
terminal doesn't say command not found it just sits with a blank line - sudo reboot did nothing and also returned no feedback from terminal.
****This is the third time already this has happened and all good until I install fordpass.  So much for the separate bridges helping to eliminate others going down

**Comment by mkellsy** [comment] 2021-04-05 18:25
I think this is is related to #30

**Comment by mkellsy** [comment] 2021-04-05 18:26
Duplicate of #27

**Closed by mkellsy** 2021-04-05 18:26 UTC
